org: eassis
app: wildtrack-media-dev
service: wildtrack-media-dev

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app
  pythonRequirements:
    zip: false

provider:
  name: aws
  runtime: python3.9
  region: us-east-2
  vpc:
    securityGroupIds:
      - sg-054276a28f1d70fb4
    subnetIds:
      - subnet-0c98aeadc2ded2714
      - subnet-0a82fccf2892f7a32
      - subnet-091845a8bbbf6e7a9
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetworkInterfaces
        - ec2:DetachNetworkInterface
      Resource: "*"
    

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'
    vpc:
      securityGroupIds:
        - sg-054276a28f1d70fb4
      subnetIds:
        - subnet-0c98aeadc2ded2714
        - subnet-0a82fccf2892f7a32
        - subnet-091845a8bbbf6e7a9
    environment:
      AWS_S3_BUCKET: ${env:AWS_S3_BUCKET}
      DB_LOCAL: ${env:DB_LOCAL}
      DB_NAME: ${env:DB_NAME}

package:
      include:
        - frontend/public

      exclude:
        - frontend/**


plugins:
  - serverless-wsgi
  - serverless-python-requirements
