import { uploadFile } from "react-s3";

window.Buffer = window.Buffer || require("buffer").Buffer;

const S3_BUCKET = process.env.REACT_APP_S3_BUCKET;
const REGION = process.env.REACT_APP_S3_REGION;
const ACCESS_KEY = process.env.REACT_APP_S3_ACCESSKEY;
const SECRET_ACCESS_KEY = process.env.REACT_APP_S3_SECRETACCESSKEY;

//@app.route(‘/get-upload-url’)

// sending uuid to s3

// observationId is id generated by the backend
//     dirName: "user/" + observationId + "/" + uuid();

const UploadImageToS3 = async (
  file,
  observationId,
  fileId,
  handleMetadataFromUpload
) => {
  const config = {
    bucketName: S3_BUCKET,
    dirName: `user/${observationId}/${fileId}`,
    region: REGION,
    accessKeyId: ACCESS_KEY,
    secretAccessKey: SECRET_ACCESS_KEY,
  };
  uploadFile(file, config)
    .then((data) => {
      // store full s3 url directoryName as attribute of media object
      // when annotation selection page is opened, make post requests for media files,
      // ids generated by the backend (_id) become the array of file ids
      handleMetadataFromUpload(data.key);
    })
    .catch((err) => console.error(err));
};

export default UploadImageToS3;
